### ISSUE TITLE
libfabric not added as a requirement?

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/asiofi#7]
I've the impression that libfabric is not added as a transitive dependency of asiofi, nor fairmq, with the net result that there are cases when one could get missing symbols at link time when linking libFairMQ built with asiofi support. Am I wrong? What is the correct way of adding libFairMQ as a dependency, when built with asiofi support?

**Comment by dennisklein** [comment]
> What is the correct way of adding libFairMQ as a dependency, when built with asiofi support?

When you have an asiofi installation, the install prefix contains `lib*/cmake` and `share/asiofi` directories:

```
├── lib64
│   └── cmake
│       └── asiofi-0.3.3
│           ├── asiofiConfig.cmake
│           ├── asiofiConfigVersion.cmake
│           ├── asiofiTargets.cmake
│           └── asiofiTargets-relwithdebinfo.cmake
└── share
    └── asiofi
        └── cmake
            └── FindOFI.cmake
```

In the consuming project (FairMQ) one would do something like:

```
find_package(asiofi)
if(asiofi_FOUND)
  foreach(dep IN LISTS asiofi_PACKAGE_DEPENDENCIES)
    find_package(${dep} ${asiofi_${dep}_VERSION} COMPONENTS ${asiofi_${dep}_COMPONENTS})
  endforeach()
endif()
```

The above works because `lib64/cmake/asiofi-*/asiofiConfig.cmake` defines:

```
(...)
set_and_check(asiofi_CMAKEMODDIR ${PACKAGE_PREFIX_DIR}/share/asiofi/cmake)

### Import cmake modules
set(CMAKE_MODULE_PATH ${asiofi_CMAKEMODDIR} ${CMAKE_MODULE_PATH})

####### Expanded from @PACKAGE_DEPENDENCIES@ by configure_package_config_file() #######

set(asiofi_PACKAGE_DEPENDENCIES Boost OFI)

set(asiofi_Boost_COMPONENTS program_options container)
set(asiofi_Boost_VERSION 1.70)
set(asiofi_OFI_COMPONENTS fi_sockets)
set(asiofi_OFI_VERSION 1.6.0)
(...)
```

asiofi itself is a private dependency of FairMQ, so a FairMQ consuming project (e.g. O2) would then import FairMQ like this:

```
find_package(FairMQ COMPONENTS ofi_transport)
if(FairMQ_FOUND)
  foreach(dep IN LISTS FairMQ_PACKAGE_DEPENDENCIES)
    if(FairMQ_${dep}_COMPONENTS)
      find_package(${dep} ${FairMQ_${dep}_VERSION} COMPONENTS ${FairMQ_${dep}_COMPONENTS})
    else()
      find_package(${dep} ${FairMQ_${dep}_VERSION})
    endif()
  endforeach()
endif()
```
(the `COMPONENTS ofi_transport` part is optional, if specified, its meaning is that a FairMQ with ofi_transport **is required**)

Because asiofi is a private dependency of FairMQ (meaning: FairMQ does not export any asiofi interfaces, it is only used in its `ofi_transport` implementation), `FairMQConfig.cmake` will **not** list asiofi as a package dependency.

```
$ cat lib64/cmake/FairMQ-*/FairMQConfig.cmake
(...)
set(FairMQ_PACKAGE_DEPENDENCIES Boost FairLogger fmt)

set(FairMQ_Boost_COMPONENTS container program_options filesystem date_time regex system log log_setup thread)
set(FairMQ_Boost_VERSION 1.70)
set(FairMQ_FairLogger_VERSION 1.6.0)
set(FairMQ_fmt_VERSION 5.3.0)
(...)
```

Only `libFairMQ.so` will have a library dependency on it (in fact only libfabric, because all asiofi code itself is header-only):

```
$ lddtree install/lib64/libFairMQ.so
libFairMQ.so => install/lib64/libFairMQ.so (interpreter => none)
    libdl.so.2 => /lib64/libdl.so.2
    librt.so.1 => /lib64/librt.so.1
    libboost_program_options.so.1.72.0 => /home/dklein/boost_1_72_0_install/lib/libboost_program_options.so.1.72.0
        libm.so.6 => /lib64/libm.so.6
    libboost_filesystem.so.1.72.0 => /home/dklein/boost_1_72_0_install/lib/libboost_filesystem.so.1.72.0
    libboost_regex.so.1.72.0 => /home/dklein/boost_1_72_0_install/lib/libboost_regex.so.1.72.0
        libicudata.so.65 => /lib64/libicudata.so.65
        libicui18n.so.65 => /lib64/libicui18n.so.65
        libicuuc.so.65 => /lib64/libicuuc.so.65
    libFairMQStateMachine.so.1.4 => install/lib64/../lib64/libFairMQStateMachine.so.1.4
    libzmq.so.5 => /lib64/libzmq.so.5
        libunwind.so.8 => /lib64/libunwind.so.8
        libsodium.so.23 => /lib64/libsodium.so.23
        libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2
            libkrb5.so.3 => /lib64/libkrb5.so.3
            libk5crypto.so.3 => /lib64/libk5crypto.so.3
            libcom_err.so.2 => /lib64/libcom_err.so.2
            libkrb5support.so.0 => /lib64/libkrb5support.so.0
                libselinux.so.1 => /lib64/libselinux.so.1
                    libpcre2-8.so.0 => /lib64/libpcre2-8.so.0
            libkeyutils.so.1 => /lib64/libkeyutils.so.1
            libcrypto.so.1.1 => /lib64/libcrypto.so.1.1
                libz.so.1 => /lib64/libz.so.1
            libresolv.so.2 => /lib64/libresolv.so.2
    libboost_container.so.1.72.0 => /home/dklein/boost_1_72_0_install/lib/libboost_container.so.1.72.0
    libFairMQTools.so.1.4 => install/lib64/../lib64/libFairMQTools.so.1.4
    libFairLogger.so.1.6 => /lib64/libFairLogger.so.1.6
    libfmt.so.6 => /lib64/libfmt.so.6
    libpthread.so.0 => /lib64/libpthread.so.0
    libfabric.so.1 => /lib64/libfabric.so.1
        librdmacm.so.1 => /lib64/librdmacm.so.1
        libefa.so.1 => /lib64/libefa.so.1
        libibverbs.so.1 => /lib64/libibverbs.so.1
        libnl-3.so.200 => /lib64/libnl-3.so.200
        libnl-route-3.so.200 => /lib64/libnl-route-3.so.200
        libpsm_infinipath.so.1 => /lib64/libpsm_infinipath.so.1
            libinfinipath.so.4 => /lib64/libinfinipath.so.4
            libuuid.so.1 => /lib64/libuuid.so.1
        libpsm2.so.2 => /lib64/libpsm2.so.2
            libnuma.so.1 => /lib64/libnuma.so.1
    libstdc++.so.6 => /lib64/libstdc++.so.6
    libgcc_s.so.1 => /lib64/libgcc_s.so.1
    libc.so.6 => /lib64/libc.so.6
    ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
```

**Comment by dennisklein** [comment]
Note: The `foreach(dep IN LISTS FairMQ_PACKAGE_DEPENDENCIES)` code is just an example, it might be different if the consuming project also has a direct dependency on any of the packages in the list and thus might want to modify the `find_package` arguments (e.g. be stricter on the version/components requirements).

**Comment by ktf** [comment]
Thanks. Indeed I think we are actually missing the bit which iterates on the dependencies.

**Comment by ktf** [comment]
Ok, I tried, but there is something which still does not work. I now have:

```cmake
find_package(FairMQ CONFIG COMPONENTS ofi_transport)
set_package_properties(FairMQ PROPERTIES TYPE REQUIRED)
if(FairMQ_FOUND)
  foreach(dep IN LISTS FairMQ_PACKAGE_DEPENDENCIES)
    if(FairMQ_${dep}_COMPONENTS)
      find_package(${dep} COMPONENTS ${FairMQ_${dep}_COMPONENTS})
    else()
      find_package(${dep})
    endif()
  endforeach()
endif()
```

but I see only:

```
FATALBoost
-- Found Boost: /opt/alisw/el7/boost/v1.74.0-42/lib/cmake/Boost-1.74.0/BoostConfi
g.cmake (found version "1.74.0") found components: container program_options file
system date_time regex system log log_setup thread
FATALFairLogger
FATALfmt
```

despite the fact FairMQ is clearly linked against libfabric:

```
[epn@alio2-cr1-flp073 Utils]$ ldd /opt/alisw/el7/FairMQ/v1.4.28-10/lib/libFairMQ.so
        linux-vdso.so.1 =>  (0x00007ffe1a8ce000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff0fbabe000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ff0fb8b6000)
        libboost_program_options.so.1.74.0 => /opt/alisw/el7/boost/v1.74.0-42/lib/libboost_program_options.so.1.74.0 (0x00007ff0fb654000)
        libboost_filesystem.so.1.74.0 => /opt/alisw/el7/boost/v1.74.0-42/lib/libboost_filesystem.so.1.74.0 (0x00007ff0fb433000)
        libboost_regex.so.1.74.0 => /opt/alisw/el7/boost/v1.74.0-42/lib/libboost_regex.so.1.74.0 (0x00007ff0fb17c000)
        libFairMQStateMachine.so.1.4 => /opt/alisw/el7/FairMQ/v1.4.28-10/lib/libFairMQStateMachine.so.1.4 (0x00007ff0faf23000)
        libzmq.so.5 => /opt/alisw/el7/ZeroMQ/v4.3.3-8/lib/libzmq.so.5 (0x00007ff0fac82000)
        libboost_container.so.1.74.0 => /opt/alisw/el7/boost/v1.74.0-42/lib/libboost_container.so.1.74.0 (0x00007ff0faa69000)
        libFairMQTools.so.1.4 => /opt/alisw/el7/FairMQ/v1.4.28-10/lib/libFairMQTools.so.1.4 (0x00007ff0fa817000)
        libFairLogger.so.1.9 => /opt/alisw/el7/FairLogger/v1.9.0-18/lib/libFairLogger.so.1.9 (0x00007ff0fa5e0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff0fa3c4000)
        libfabric.so.1 => not found
        libstdc++.so.6 => /opt/alisw/el7/GCC-Toolchain/v7.3.0-alice2-12/lib64/libstdc++.so.6 (0x00007ff0fa03d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff0f9d3b000)
        libgcc_s.so.1 => /opt/alisw/el7/GCC-Toolchain/v7.3.0-alice2-12/lib64/libgcc_s.so.1 (0x00007ff0f9b24000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff0f9756000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff0fc206000)
```

**Comment by dennisklein** [comment]
> but I see only:
>
> ```
> FATALBoost
> -- Found Boost: /opt/alisw/el7/boost/v1.74.0-42/lib/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: container program_options filesystem date_time regex system log log_setup thread
> FATALFairLogger
> FATALfmt
> ```

This is correct. Why do you need to see the OFI dependency here?

> ```
> libfabric.so.1 => not found
> ```

This is strange, did you disable `RUNPATH` when compiling FairMQ?

**Comment by ktf** [comment]
Actually I think the problem is the opposite. RUNPATH does not work in our case because our packages need to be relocatable. Is there any way to disable RUNPATH when compiling asiofi? We guarantee that LD_LIBRARY_PATH will point to the correct place.

**Comment by dennisklein** [comment]
> Actually I think the problem is the opposite. RUNPATH does not work in our case because our packages need to be relocatable. Is there any way to disable RUNPATH when compiling asiofi? We guarantee that LD_LIBRARY_PATH will point to the correct place.

`LD_LIBRARY_PATH` overrides `RUNPATH` - that is why we use it, so alibuild and similar use cases are not broken. Only the old `RPATH` on Linux, however, had a higher priority. (Linux `RUNPATH` basically models the same behaviour as macOS `RPATH`).

**Comment by ktf** [comment]
To be clear, this:

https://github.com/AliceO2Group/AliceO2Group.github.io/pull/43/files

is what I need to do in order to compile on linux from a relocated set of binaries. Any idea of what might be go wrong?

**Comment by dennisklein** [comment]
```
export LD_LIBRARY_PAYH=/opt/alisw/el7/ofi/v1.7.1-13/lib:$LD_LIBRARY_PATH
```

Shouldn't aliBuild construct the `LD_LIBRARY_PATH` and add `/opt/alisw/el7/ofi/v1.7.1-13/lib` to it? Maybe some issue in the recipe?

**Comment by dennisklein** [comment]
The [`ofi.sh`](https://github.com/alisw/alidist/blob/master/ofi.sh) recipe is missing those lines: https://github.com/alisw/alidist/blob/c78db6583793fee2c6acdb2c791651ac1342de87/asiofi.sh#L54-L55

edit: or maybe not, hmm

**Comment by ktf** [comment]
no, indeed. And in any case they are not used for building.

**Comment by dennisklein** [comment]
maybe far fetched, but is there by any chance any *find and replace operation* done on the already generated ld library search path during relocation? I am thinking maybe such a find operation may be matching too greedily (because both packages end in `ofi`) and replace too much and as a result the `ofi` lib path is broken? (and since `asiofi` does not have any library, a broken `asiofi` lib path would not be visible...)

**Comment by ktf** [comment]
Ok... It looks like the problem is that we do not have the correct runtime environment to actually run the created executables as part of the CMake. Thank you for the discussion.
